version: "3"
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.36
    ports:
      - "${ADVERTISED_HTTP_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PERSISTENCE_ENABLED: "false"
      JAVA_TOOL_OPTIONS: >
        -Dkalix.proxy.eventing.support=kafka
      # those variables are defined in the .env file
      # when running multiple services on your local machine, make sure that
      # the ports are unique by editing the corresponding .env files
      ADVERTISED_HTTP_PORT: ${ADVERTISED_HTTP_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      # configuring kafka broker used for eventing
      BROKER_SERVERS: kafka-1:9091

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "29091:29091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9091,PLAINTEXT_HOST://localhost:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-1:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-1
    ports:
      - "8081:8081"
    restart: always
    environment:
      - SERVER_PORT=8081
      - KAFKA_CLUSTERS_0_NAME=INPUT
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9091
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
